apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/instance: vm-operator
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    platform.monitoring.app: victoriametrics-operator
  name: victoriametrics-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: vm-operator
      app.kubernetes.io/name: victoriametrics-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: vm-operator
        app.kubernetes.io/name: victoriametrics-operator
        app.kubernetes.io/component: victoriametrics
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: monitoring-operator
    spec:
      containers:
      - args:
        - --zap-log-level=info
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: victoriametrics-operator
        - name: VM_PSPAUTOCREATEENABLED
          value: "false"
        - name: VM_ENABLEDPROMETHEUSCONVERTEROWNERREFERENCES
          value: "true"
        - name: VM_VMALERTDEFAULT_CONFIGRELOADERMEMORY
          value: 50Mi
        - name: VM_VMAGENTDEFAULT_CONFIGRELOADERMEMORY
          value: 50Mi
        - name: VM_VMALERTMANAGER_CONFIGRELOADERMEMORY
          value: 50Mi
        image: victoriametrics/operator:v0.33.0
        imagePullPolicy: IfNotPresent
        name: victoriametrics-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9443
          name: webhook
          protocol: TCP
        resources: 
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: monitoring-victoriametrics-operator
      serviceAccountName: monitoring-victoriametrics-operator
      terminationGracePeriodSeconds: 30
