apiVersion: v1
kind: Service
metadata:
  name: kubelet
  namespace: monitoring
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    k8s-app: kubelet
spec:
  ports:
    - name: https-metrics
      protocol: TCP
      port: 10250
      targetPort: 10250
    - name: http-metrics
      protocol: TCP
      port: 10255
      targetPort: 10255
    - name: cadvisor
      protocol: TCP
      port: 4194
      targetPort: 4194
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
