apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: victoriametrics-operator
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: webhook
      port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: victoriametrics-operator