apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: vmoperator
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: vmoperator
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 30s
  jobLabel: vmoperator
  namespaceSelector: {}
  selector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - victoriametrics-operator
