apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-k8s
  labels:
    name: alertmanager-k8s
    app.kubernetes.io/name: alertmanager-k8s
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
