apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-alertmanager
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator