# Default values for stackdriver-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deploy a stackdriver-exporter
#
# Allow to enable deploy stackdriver-exporter.
# Type: boolean
# Mandatory: no
# Default: false
#
install: false

# A name of a microservice to deploy with.
# This name will be used as name of the microservice deployment and in labels.
name: "stackdriver-exporter"

# Number of exporters to run
replicas: 1

# A Docker image to deploy the stackdriver-exporter
#image: "prometheuscommunity/stackdriver-exporter:v0.12.0"

# Image pull policy to use for stackdriver-exporter deployment
imagePullPolicy: IfNotPresent

# The resources describes the compute resource requests and limits for single Pod.
# Ref: https://kubernetes.io/docs/user-guide/compute-resources/
# Type: object
# Mandatory: no
#
resources: {}
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 100m
#    memory: 128Mi

# SecurityContext holds pod-level security attributes.
# Mandatory: no
#
securityContext: {}
  # The UID to run the entrypoint of the container process.
  # Defaults to user specified in image metadata if unspecified.
  #
  # Mandatory: no
  # runAsUser: 2000

  # A special supplemental group that applies to all containers in a pod.
  # Some volume types allow the Kubelet to change the ownership of that volume
  # to be owned by the pod:
  #   1. The owning GID will be the FSGroup
  #   2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
  #   3. The permission bits are OR'd with rw-rw----
  # If unset, the Kubelet will not modify the ownership and permissions of any volume.
#
# Mandatory: no
# fsGroup: 2000

# Service configuration for stackdriver-exporter
# Type: object
# Mandatory: no
#
service:
  # Type of stackdriver-exporter service
  # Type: string
  # Mandatory: no
  # Default: ClusterIP
  #
  type: ClusterIP

  # Port of stackdriver-exporter which use in service
  # Type: int
  # Mandatory: no
  # Default: 9255
  #
  port: 9255

  # Annotations set which will be created in service
  # Type: map[string]string
  # Mandatory: no
  # Default: {}
  #
  annotations: {}

stackdriver:
  # The Google Project ID to gather metrics for
  projectId: "FALSE"
  # An existing secret which contains credentials.json
  serviceAccountSecret: ""
  # Provide custom key for the existing secret to load credentials.json from
  serviceAccountSecretKey: ""
  # A service account key JSON file. Must be provided when no existing secret is used, in this case a new secret will be created holding this service account
  serviceAccountKey: ""
  # Max number of retries that should be attempted on 503 errors from Stackdriver
  maxRetries: 0
  # How long should Stackdriver_exporter wait for a result from the Stackdriver API
  httpTimeout: 10s
  # Max time between each request in an exp backoff scenario
  maxBackoff: 5s
  # The amount of jitter to introduce in an exp backoff scenario
  backoffJitter: 1s
  # The HTTP statuses that should trigger a retry
  retryStatuses: 503
  # Drop metrics from attached projects and fetch `project_id` only
  dropDelegatedProjects: false
  metrics:
    # The prefixes to gather metrics for, we default to just CPU metrics.
    typePrefixes: 'compute.googleapis.com/instance/cpu'
    # The frequency to request
    interval: '5m'
    # How far into the past to offset
    offset: '0s'
    # Offset for the Google Stackdriver Monitoring Metrics interval into the past by the ingest delay from the metric's metadata.
    ingestDelay: false

# If specified, the pod's scheduling constraints
# More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#affinity-v1-core
# Type: object
# Mandatory: no
# Default: not set
#
affinity: {}

# Additional arguments for stackdriver-exporter container.
# Type: list[string]
# Mandatory: no
# Default: []
#
extraArgs: []

# Allow define which Nodes the Pods are scheduled on.
# Type: map[string]string
# Mandatory: no
# Default: not set
#
nodeSelector: {}

# Tolerations allow the pods to schedule onto nodes with matching taints.
# Type: list[object]
# Mandatory: no
#
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
#   value: "value"
#   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

# ServiceAccount setting.
# Type: object
# Mandatory: no
#
serviceAccount:
  # Specifies whether a ServiceAccount should be created.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  create: true

  # The name of the ServiceAccount to use.
  # Type: string
  # Mandatory: no
  # Default: stackdriver-exporter
  #
  name: stackdriver-exporter

  # Will add the provided map to the annotations for the created serviceAccount.
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  annotations: {}

  # Will add the provided map to the labels for the created serviceAccount.
  # Type: map[string]string
  # Mandatory: no
  # Default: not set
  #
  labels: {}

# Service monitor for pulling metrics
# Type: object
# Mandatory: no
#
serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  install: true

  # Set how frequently Prometheus should scrape
  interval: 2m

  # Set path to stackdriver-exporter telemetry-path
  telemetryPath: /metrics

  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  labels:
    app.kubernetes.io/component: monitoring

  # Set timeout for scrape
  timeout: 30s

  # Set relabelings for the ServiceMonitor, use to apply to samples before scraping
  relabelings: []

  # Set metricRelabelings for the ServiceMonitor, use to apply to samples for ingestion
  metricRelabelings: []

  # Example - note the Kubernetes convention of camelCase instead of Prometheus' snake_case
  # metricRelabelings:
  #   - sourceLabels: [dbinstance_identifier]
  #     action: replace
  #     replacement: mydbname
  #     targetLabel: dbname

# Annotations is an unstructured key value map stored
# with a resource that may be set by external tools to store and retrieve arbitrary metadata.
# They are not queryable and should be preserved when modifying objects.
# More info: https://kubernetes.io/docs/user-guide/annotations
# Type: map[string]string
# Mandatory: no
# Default: not set
#
annotations: {}
#  annotation-key: annotation-value

# Map of string keys and values that can be used to organize and categorize (scope and select) objects.
# May match selectors of replication controllers and services.
# More info: https://kubernetes.io/docs/user-guide/labels
# Type: map[string]string
# Mandatory: no
# Default: not set
#
labels: {}
#  label-key: label-value

# PriorityClassName assigned to the Pods to prevent them from evicting.
# Type: string
# priorityClassName: "priorityClassName"
