{{- if and .Values.cleanup.deleteCRs .Values.global.privilegedRights -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vm.cleanup.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vm.cleanup.rbac.fullname" . }}
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ include "vm.cleanup.rbac.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vmauths
      - vmusers
      - vmagents
      - vmalerts
      - vmsingles
      - vmalertmanagers
      - vmclusters
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - list
      - watch
      - patch
      - update
{{- end -}}
