{{- if and .Values.cleanup.deleteCRs .Values.global.privilegedRights -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vm.cleanup.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vm.cleanup.rbac.fullname" . }}
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ include "vm.cleanup.rbac.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vm.cleanup.rbac.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vm.cleanup.rbac.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
