{{- if and .Values.install .Values.clusterRole.install .Values.global.privilegedRights }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "prometheusAdapter.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "prometheusAdapter.rbac.fullname" . }}
    app.kubernetes.io/instance: {{ template "prometheusAdapter.instance" . }}
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
rules:
  # Need to discover CRs in all namespaces
  - apiGroups:
      - monitoring.qubership.org
    resources:
      - customscalemetricrules
      - prometheusadapters
    verbs:
      - get
      - list
      - watch

  # Need to update statuses and finalizers for all found CRs
  - apiGroups:
      - monitoring.qubership.org
    resources:
      - customscalemetricrules/status
      - customscalemetricrules/finalizers
      - prometheusadapters/status
      - prometheusadapters/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  # Need to create, update and remove ClusterRoles and ClusterRoleBingind
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete

  # Permissions for leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - services
      - pods
      - serviceaccounts
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - authorization.k8s.io
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
{{- if or .Values.enableResourceMetrics .Values.enableCustomMetrics }}
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - custom.metrics.k8s.io
    resources:
      - '*'
{{- end }}
{{- end }}
