apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-resource-rules
  labels:
    app.kubernetes.io/name: prometheus-adapter-resource-rules
    app.kubernetes.io/instance: {{ template "prometheusAdapter.instance" . }}
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
data:
  config.yaml: |
  {{- if .Values.configResourceMetrics }}
    {{- toYaml .Values.configResourceMetrics | nindent 4 }}
  {{- else }}
    resourceRules:
      cpu:
        containerLabel: container
        containerQuery: |
          sum by (<<.GroupBy>>) (irate (container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!="",pod!=""}[4m]))
        nodeQuery: |
          sum by (<<.GroupBy>>) (irate(node_cpu_seconds_total{<<.LabelMatchers>>}[4m]))
        resources:
          overrides:
            namespace:
              resource: namespace
            node:
              resource: node
            pod:
              resource: pod
      memory:
        containerLabel: container
        containerQuery: |
          sum by (<<.GroupBy>>) (container_memory_working_set_bytes{<<.LabelMatchers>>,container!="",pod!=""})
        nodeQuery: |
          sum by (<<.GroupBy>>) (node_memory_working_set_bytes{<<.LabelMatchers>>})
        resources:
          overrides:
            node:
              resource: node
            namespace:
              resource: namespace
            pod:
              resource: pod
      window: 5m
  {{- end }}