{{- if .Values.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter-operator
  labels:
    app.kubernetes.io/name: prometheus-adapter-operator
    app.kubernetes.io/instance: {{ template "prometheusAdapter.instance" . }}
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
    {{- if .Values.operator.labels }}
      {{- toYaml .Values.operator.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.operator.annotations }}
  annotations:
    {{- toYaml .Values.operator.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-adapter-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-adapter-operator
        app.kubernetes.io/instance: {{ cat "prometheus-adapter-operator-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
        {{- include "prometheusAdapter.commonLabels" . | nindent 8 }}
        app.kubernetes.io/managed-by: Helm
      {{- if .Values.operator.labels }}
        {{- toYaml .Values.operator.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.annotations }}
      annotations:
        {{- toYaml .Values.operator.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.operator.priorityClassName }}
      priorityClassName: {{ .Values.operator.priorityClassName | quote }}
      {{- end }}
      securityContext:
        {{ include "prometheusAdapter.operator.securityContext" . }}
      serviceAccountName: prometheus-adapter-operator
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity: {{- toYaml .Values.operator.affinity | nindent 8 }}
      nodeSelector: {{- toYaml .Values.operator.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.operator.tolerations | nindent 8 }}
      containers:
      - name: prometheus-adapter-operator
        command: ["/manager"]
        args:
          - "--enable-leader-election"
        image: {{ template "prometheusAdapter.operator.image" . }}
        imagePullPolicy: IfNotPresent
        resources:
          {{ include "prometheusAdapter.operator.resources" $ }}
{{- end }}
