{{- if and .Values.install .Values.operator.tlsEnabled (not .Values.operator.tlsConfig.existingSecret) }}
{{- if not (and .Values.operator.tlsConfig.caSecret .Values.operator.tlsConfig.certSecret .Values.operator.tlsConfig.keySecret) }}
{{- if .Values.operator.tlsConfig.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "prometheus-adapter-client-tls-secret" .Values.operator.tlsConfig.createSecret.secretName }}
  labels:
    app.kubernetes.io/name: {{ default "prometheus-adapter-client-tls-secret" .Values.operator.tlsConfig.createSecret.secretName }}
    app.kubernetes.io/instance: {{ template "prometheusAdapter.instance" . }}
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.operator.tlsConfig.createSecret.ca }}
  ca.crt: {{ .Values.operator.tlsConfig.createSecret.ca | b64enc | quote }}
  {{- end }}
  {{- if .Values.operator.tlsConfig.createSecret.cert }}
  tls.crt: {{ .Values.operator.tlsConfig.createSecret.cert | b64enc | quote }}
  {{- end }}
  {{- if .Values.operator.tlsConfig.createSecret.key }}
  tls.key: {{ .Values.operator.tlsConfig.createSecret.key | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}