{{- if and .Values.install .Values.auth }}
{{- if and .Values.auth.basicAuth .Values.auth.basicAuth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-adapter-client-basic-auth
  labels:
    app.kubernetes.io/name: prometheus-adapter-client-basic-auth
    app.kubernetes.io/instance: {{ template "prometheusAdapter.instance" . }}
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.auth.basicAuth.createSecret.username }}
  password: {{ .Values.auth.basicAuth.createSecret.password }}
{{- end }}
{{- end }}
