{{- if .Values.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-adapter-operator
  labels:
    app.kubernetes.io/name: prometheus-adapter-operator
    app.kubernetes.io/instance: {{ template "prometheusAdapter.instance" . }}
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
{{- end }}
