apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    k8s-app: prometheus-pod-monitor
  name: prometheus-pod-monitor
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: web
    scheme: http
  jobLabel: k8s-app
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
