apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator