---
version: "2"
checks:
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 50
  return-statements:
    config:
      threshold: 5

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - go
  gofmt:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true
