{{- if and .Values.install .Values.global.privilegedRights .Values.rbac.createClusterRole }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "cloudEventsExporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "cloudEventsExporter.fullname" . }}
    app.kubernetes.io/component: cloud-events-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "cloudEventsExporter.instance" . }}
    app.kubernetes.io/version: {{ template "cloudEventsExporter.version" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}