{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: cloud-events-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "cloudEventsExporter.instance" . }}
    app.kubernetes.io/version: {{ template "cloudEventsExporter.version" . }}
data:
{{- if .Values.filtering }}
  filtering.yaml: |-
    sinks:
      - name: "metrics"
        {{- toYaml .Values.filtering | nindent 8 }}
{{- else }}
  filtering.yaml: ""
{{- end }}
{{- end }}
