apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-extra-vars
  labels:
    app.kubernetes.io/name: grafana-extra-vars
    app.kubernetes.io/instance: {{ cat "grafana-extra-vars-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
{{- if .Values.extraVars }}
data:
  {{- range $key, $val := .Values.extraVars }}
  {{ $key | quote | indent 4}}: {{ $val | quote }}
  {{- end}}
  {{- if .Values.imageRenderer.install }}
    {{- if not .Values.extraVars.GF_RENDERING_SERVER_URL }}
      "GF_RENDERING_SERVER_URL": "http://grafana-image-renderer:8081/render"
    {{- end }}
    {{- if not .Values.extraVars.GF_RENDERING_CALLBACK_URL }}
      "GF_RENDERING_CALLBACK_URL": "http://grafana-service:3000/"
    {{- end }}
  {{- end }}
{{- else }}
data:
{{- end }}

