{{- $oauth2Config := (lookup "v1" "Secret" .Release.Namespace "oauth2-proxy-config") }}
{{- if .Values.extraVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-extra-vars-secret
  labels:
    app.kubernetes.io/name: grafana-extra-vars-secret
    app.kubernetes.io/instance: {{ cat "grafana-extra-vars-secret-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
  {{- if $oauth2Config }}
    {{- $oauth2Config = (get $oauth2Config.data "oauth2-proxy.cfg") }}
    {{- $config := $oauth2Config | b64dec }}
    {{- $clientIDRegex := `client_id\s*=\s*"([^"]+)"` }}
    {{- $clientSecretRegex := `client_secret\s*=\s*"([^"]+)"` }}
    {{- $clientIdMatch := $config | regexFind $clientIDRegex | trimPrefix "client_id = \"" | trimSuffix "\"" }}
    {{- $clientSecretMatch := $config | regexFind $clientSecretRegex | trimPrefix "client_secret = \"" | trimSuffix "\"" }}
    {{- if and $clientIdMatch $clientSecretMatch }}
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ $clientIdMatch }}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ $clientSecretMatch }}
  {{- range $key, $val := .Values.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
    {{- else }}
stringData:
  {{- range $key, $val := .Values.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
    {{- end }}
  {{- else }}
stringData:
  {{- range $key, $val := .Values.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-extra-vars-secret
  labels:
    app.kubernetes.io/name: grafana-extra-vars-secret
    app.kubernetes.io/instance: {{ cat "grafana-extra-vars-secret-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
  {{- if $oauth2Config }}
    {{- $oauth2Config = (get $oauth2Config.data "oauth2-proxy.cfg") }}
    {{- $config := $oauth2Config | b64dec }}
    {{- $clientIDRegex := `client_id\s*=\s*"([^"]+)"` }}
    {{- $clientSecretRegex := `client_secret\s*=\s*"([^"]+)"` }}
    {{- $clientIdMatch := $config | regexFind $clientIDRegex | trimPrefix "client_id = \"" | trimSuffix "\"" }}
    {{- $clientSecretMatch := $config | regexFind $clientSecretRegex | trimPrefix "client_secret = \"" | trimSuffix "\"" }}
    {{- if and $clientIdMatch $clientSecretMatch }}
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ $clientIdMatch }}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ $clientSecretMatch }}
    {{- else }}
data: {}
    {{- end }}
  {{- else }}
data: {}
  {{- end }}
{{- end }}
