apiVersion: v1
kind: Secret
metadata:
  name: grafana-ldap-config
  labels:
    app.kubernetes.io/name: grafana-ldap-config
    app.kubernetes.io/instance: {{ cat "grafana-ldap-config-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
{{- if .Values.ldapConfig }}
  ldap.toml: |-
    {{ .Values.ldapConfig | nindent 4}}
{{- else }}
  ldap.toml: ""
{{- end }}
