{{- if and (.Values.monitoringOperator.podMonitor) (.Values.monitoringOperator.podMonitor.install) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitoring-operator
  labels:
    app.kubernetes.io/name: monitoring-operator
    app.kubernetes.io/component: monitoring-operator
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "monitoring.operator.version" . }}
spec:
  podMetricsEndpoints:
  - interval: {{ .Values.monitoringOperator.podMonitor.interval }}
    port: http
    scheme: http
    metricRelabelings:
      {{- toYaml .Values.monitoringOperator.podMonitor.metricRelabelings | nindent 6 }}
    relabelings:
      {{- toYaml .Values.monitoringOperator.podMonitor.relabelings | nindent 6 }}
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.monitoringOperator.name }}
{{- end }}
