{{- if .Values.monitoringOperator.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoringOperator.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.monitoringOperator.serviceAccount.name }}
    app.kubernetes.io/component: monitoring-operator
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "monitoring.operator.version" . }}
{{- end }}
