{{- if and .Values.install .Values.config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-config
    app.kubernetes.io/instance: {{ cat .Values.name "-config-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: promxy
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "promxy.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
data:
  config.yaml: |
  {{- if .Values.config.detailedConfig }}
    {{- toYaml .Values.config.detailedConfig | nindent 4 }}
  {{- else }}
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    promxy:
      server_groups:
        {{- range .Values.config.serverGroups }}
        - static_configs:
            - targets:
                - {{ .address }}
          labels:
            cluster: {{ .label }}
          anti_affinity: 10s
          scheme: {{ default "http" .scheme }}
          http_client:
            tls_config:
              insecure_skip_verify: true
          ignore_error: true
        {{- end }}
  {{- end }}
{{- end }}
