apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: monitoring-prometheus-operator
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - "create"
      - "get"
      - "list"
      - "watch"
      - "update"

  - apiGroups:
      - "storage.k8s.io"
    resources:
      - volumeattachments
      - storageclasses
    verbs:
      - 'get'
      - 'list'
      - 'watch'

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch

  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - alertmanagers
      - alertmanagers/status
      - alertmanagers/finalizers
      - alertmanagerconfigs
      - prometheuses
      - prometheuses/finalizers
      - prometheuses/status
      - prometheusagents
      - prometheusagents/status
      - thanosrulers
      - thanosrulers/finalizers
      - servicemonitors
      - podmonitors
      - probes
      - prometheusrules
      - scrapeconfigs
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"

  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
      - secrets
      - configmaps
    verbs:
      - "get"
      - "list"
      - "watch"

  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - 'get'
      - 'list'
      - 'watch'
