apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-operator-pod-monitor
  labels:
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: http
    scheme: http
  jobLabel: k8s-app
  namespaceSelector: {}
  selector:
    matchLabels:
      platform.monitoring.app: prometheus-operator
