apiVersion: v1
kind: Service
metadata:
  labels:
    platform.monitoring.app: prometheus-operator
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: prometheus-operator
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    platform.monitoring.app: prometheus-operator