{{- if .Values.tlsConfig }}
{{- if .Values.tlsConfig.generateCerts }}
{{- if and .Values.tlsConfig.generateCerts.enabled (not (.Values.tlsConfig.generateCerts.clusterIssuerName)) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prometheus-tls-issuer
  labels:
    app.kubernetes.io/name: prometheus-tls-issuer
    app.kubernetes.io/instance: {{ cat "prometheus-tls-issuer-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}
{{- end }}
