apiVersion: v1
kind: Secret
metadata:
  name: additional-alertmanager-configs
  labels:
    app.kubernetes.io/name: additional-alertmanager-configs
    app.kubernetes.io/instance: {{ cat "additional-alertmanager-configs-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
{{- if .Values.additionalAlertManager }}
stringData:
  alertmanager-additional.yaml: |-
    {{- toYaml .Values.additionalAlertManager | nindent 4 }}
{{- else }}
data:
  alertmanager-additional.yaml: ""
{{- end }}
