apiVersion: v1
kind: Secret
metadata:
  name: additional-alertrelabel-configs
  labels:
    app.kubernetes.io/name: additional-alertrelabel-configs
    app.kubernetes.io/instance: {{ cat "additional-alertrelabel-configs-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
{{- if .Values.additionalAlertRelabel }}
stringData:
  alertrelabel-additional.yaml: |-
    {{- toYaml .Values.additionalAlertRelabel | nindent 4 }}
{{- else }}
data:
  alertrelabel-additional.yaml: ""
{{- end }}
