apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  labels:
    app.kubernetes.io/name: additional-scrape-configs
    app.kubernetes.io/instance: {{ cat "additional-scrape-configs-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
{{- if .Values.additionalScrape }}
stringData:
  prometheus-additional.yaml: |-
    {{- toYaml .Values.additionalScrape | nindent 4 }}
{{- else }}
data:
  prometheus-additional.yaml: ""
{{- end }}
