{{- if .Values.tlsConfig }}
{{- if .Values.tlsConfig.createSecret}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ default "prometheus-tls" .Values.tlsConfig.createSecret.name }}
  labels:
    app.kubernetes.io/name: {{ default "prometheus-tls" .Values.tlsConfig.createSecret.name }}
    app.kubernetes.io/instance: {{ cat (default "prometheus-tls" .Values.tlsConfig.createSecret.name) "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data: {}
stringData:
  {{- if .Values.tlsConfig.createSecret.ca }}
  ca.crt:
    {{- toYaml .Values.tlsConfig.createSecret.ca | nindent 4 }}
  {{- end }}
  {{- if .Values.tlsConfig.createSecret.cert }}
  tls.crt:
    {{- toYaml .Values.tlsConfig.createSecret.cert | nindent 4 }}
  {{- end }}
  {{- if .Values.tlsConfig.createSecret.key }}
  tls.key:
    {{- toYaml .Values.tlsConfig.createSecret.key | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
