{{- if and .Values.install  .Values.serviceMonitor.enabled }}
{{- range .Values.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Values.name }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ $.Values.name }}-{{ .name }}
    app.kubernetes.io/instance: {{ cat $.Release.Namespace "-" $.Values.name "-" .name "-" $.Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "jsonExporter.image" $ }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
spec:
  endpoints:
  - port: {{ $.Values.service.name }}
    scheme: {{ $.Values.serviceMonitor.scheme }}
    path: "/probe"
    interval: {{ .interval | default $.Values.serviceMonitor.defaults.interval }}
    {{- if $.Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .scrapeTimeout | default $.Values.serviceMonitor.defaults.scrapeTimeout }}
    {{- end }}
    params:
      target:
      - {{ .url }}
      {{- if .module }}
      module:
      - {{ .module }}
      {{- end }}
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: {{ .url }}
      - sourceLabels: [target]
        targetLabel: target
        replacement: {{ .name }}
      {{- if .additionalMetricsRelabels }}
        {{- toYaml .additionalMetricsRelabels | nindent 6 }}
      {{- else if $.Values.serviceMonitor.defaults.additionalMetricsRelabels }}
        {{- toYaml $.Values.serviceMonitor.defaults.additionalMetricsRelabels | nindent 6 }}
      {{- else }}
        {{- /* Won't insert anything */}}
      {{- end }}
  jobLabel: {{ $.Release.Name }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ $.Values.name }}
{{- end }}
{{- end }}
