{{- if .Values.security }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials-temp
  labels:
    app.kubernetes.io/name: grafana-admin-credentials-temp
    app.kubernetes.io/instance: {{ cat "grafana-admin-credentials-temp-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.security.admin_user }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.security.admin_password }}
{{- end }}
