{{- if and .Values.auth .Values.oAuthProxy }}
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: oauth2-proxy-config
  labels:
    app.kubernetes.io/name: oauth2-proxy-config
    app.kubernetes.io/component: oauth2-proxy
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ cat "oauth2-proxy-config-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
stringData:
  oauth2-proxy.cfg: |-
    cookie_secret = "Z0lKZ64IEMCv8XQM9smEDw=="
    email_domains = [
    "*"
    ]
    provider = "keycloak"
    client_id = "{{ .Values.auth.clientId }}"
    client_secret = "{{ .Values.auth.clientSecret }}"
    login_url = "{{ .Values.auth.loginUrl }}"
    redeem_url = "{{ .Values.auth.tokenUrl }}"
    validate_url = "{{ .Values.auth.userInfoUrl }}"
    ssl_insecure_skip_verify = {{ default false .Values.auth.tlsConfig.insecureSkipVerify }}
{{- if .Values.auth.tlsConfig }}
{{- if .Values.auth.tlsConfig.caSecret }}
    provider_ca_files = "{{ printf "/etc/oauth-proxy/certificates/%s/%s" .Values.auth.tlsConfig.caSecret.name .Values.auth.tlsConfig.caSecret.key }}"
{{- end }}
{{- if .Values.auth.tlsConfig.certSecret }}
    tls_cert_file = "{{ printf "/etc/oauth-proxy/certificates/%s/%s" .Values.auth.tlsConfig.certSecret.name .Values.auth.tlsConfig.certSecret.key }}"
{{- end }}
{{- if .Values.auth.tlsConfig.keySecret }}
    tls_key_file = "{{ printf "/etc/oauth-proxy/certificates/%s/%s" .Values.auth.tlsConfig.keySecret.name .Values.auth.tlsConfig.keySecret.key }}"
{{- end }}
{{- end }}
{{- if .Values.auth.basicAuthPwd }}
    basic_auth_password = "{{ .Values.auth.basicAuthPwd }}"
{{- end }}
    http_address = ":9092"
    cookie_secure = false
    scope = "openid profile"
    request_logging_format = "{{ "[{{.Timestamp}}][INFO]{{.Client}} - {{.Username}} {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}" }}"
    auth_logging_format="{{ "[{{.Timestamp}}][INFO][audit_log_type][{{.Status}}] {{.Client}} - {{.Username}} {{.Host}} {{.Message}}" }}"
{{- end }}
