{{- if .Values.grafana }}
{{- if .Values.grafana.install }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-extra-vars-secret
  labels:
    app.kubernetes.io/name: grafana-extra-vars-secret
    app.kubernetes.io/instance: {{ cat "grafana-extra-vars-secret-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
{{- if .Values.auth}}
{{- if .Values.auth.clientId}}
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ .Values.auth.clientId }}
{{- end}}
{{- if .Values.auth.clientSecret}}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.auth.clientSecret }}
{{- end}}
{{- end}}
{{- if .Values.grafana.extraVarsSecret }}
  {{- range $key, $val := .Values.grafana.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
