apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-node-exporter
  labels:
    app.kubernetes.io/component: node-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator