apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: monitoring-vmagent
rules:
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - ''
  resources:
    - nodes
    - nodes/metrics
    - nodes/proxy
    - services
    - endpoints
    - pods
    - endpointslices
    - namespaces
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - networking.k8s.io
    - extensions
  resources:
    - ingresses
- verbs:
    - get
    - list
    - watch
  nonResourceURLs:
    - /metrics
    - /metrics/resources
- verbs:
    - get
  apiGroups:
    - route.openshift.io
    - image.openshift.io
  resources:
    - routers/metrics
    - registry/metrics