{{- if and .Values.install .Values.global.privilegedRights }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "version-exporter.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "version-exporter.rbac.fullname" . }}
    app.kubernetes.io/component: version-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "version-exporter.instance" . }}
    app.kubernetes.io/version: {{ template "version-exporter.version" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}