{{- if and .Values.install .Values.extraVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.secretName }}
    app.kubernetes.io/component: version-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "version-exporter.instance" . }}
    app.kubernetes.io/version: {{ template "version-exporter.version" . }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
{{- end }}
