{{- if and .Values.install .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/component: version-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "version-exporter.instance" . }}
    app.kubernetes.io/version: {{ template "version-exporter.version" . }}
    {{- if .Values.service.labels }}
      {{ toYaml .Values.service.labels | indent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
