apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: platform-monitoring-prometheus
  labels:
    name: platform-monitoring-prometheus
    app.kubernetes.io/name: platform-monitoring-prometheus
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  name: platform-monitoring.yaml
  datasources:
  - access: proxy
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 30s
      tlsSkipVerify: true
    name: Platform Monitoring Prometheus
    type: prometheus
    url: 'http://prometheus-operated:9090'
    version: 1
  - access: proxy
    editable: true
    isDefault: false
    jsonData:
      timeInterval: 30s
      tlsSkipVerify: true
    name: Platform Monitoring Promxy
    type: prometheus
    url: 'http://promxy:9090'
    version: 1