apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
    name: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  ingress:
    enabled: false
  livenessProbeSpec:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10
  readinessProbeSpec:
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 10