apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  labels:
    name: vmalert
    app.kubernetes.io/name: vmalert
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  annotations:
    operator.victoriametrics.com/vmalert-deduplicate-rules: "true"
  name: k8s
spec:
  replicaCount: 1
  evaluationInterval: "30s"
  resources: {}
  securityContext:
    fsGroup: 2000
    runAsUser: 2000

  # Enable discovery all CRs if labelSelectors is empty
  selectAllByDefault: true

  # Selector to discovery CRs
  # Exclude the OpenShift Monitoring configurations
  ruleSelector: {}
  ruleNamespaceSelector:
    matchExpressions:
      - key: openshift.io/cluster-monitoring
        operator: NotIn
        values: ["true"]
