# Default values for blackbox-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Allow to enable deploy blackbox-exporter
# Type: boolean
# Mandatory: no
# Default: false
#
install: false

# A name of a microservice to deploy with.
# This name will be used as name of the microservice deployment and in labels.
name: blackbox-exporter

# A Docker image to deploy the blackbox-exporter.
# image: prom/blackbox-exporter:v0.19.0

# Allows deploying blackbox-exporter as DaemonSet instead of Deployment.
# Type: boolean
# Mandatory: no
# Default: false
#
asDaemonSet: false

# Security Context for a container.
# Type: object
# Mandatory: no
#
# containerSecurityContext: {}

# If the configuration is managed as secret outside the chart, using SealedSecret for example,
# provide the name of the secret here. If secretConfig is set to true, configExistingSecretName will be ignored
# in favor of the config value.
# Type: string
# Mandatory: no
# Default: ""
#
configExistingSecretName: ""

# Store the configuration as a `Secret` instead of a `ConfigMap`, useful in case it contains sensitive data.
# Type: boolean
# Mandatory: no
# Default: false
#
secretConfig: false

# Configuration of blackbox-exporter modules.
# Ref: https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
# Type: object
# Mandatory: yes
#
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
    icmp:
      prober: icmp
      timeout: 5s
      icmp:
        preferred_ip_protocol: "ip4"
        source_ip_address: "127.0.0.1"
    tcp:
      prober: tcp
      timeout: 5s
      tcp:
        preferred_ip_protocol: "ip4"
        source_ip_address: "127.0.0.1"

# The resources describes the compute resource requests and limits for single Pod.
# Ref: https://kubernetes.io/docs/user-guide/compute-resources/
# Type: object
# Mandatory: no
#
resources: {}
#   limits:
#     memory: 300Mi
#   requests:
#     memory: 50Mi

# Port for blackbox-exporter service.
# Type: integer
# Mandatory: no
# Default: 9115
#
servicePort: 9115

# Only changes container port. Application port can be changed with extraArgs (--web.listen-address=:9115).
# https://github.com/prometheus/blackbox_exporter/blob/998037b5b40c1de5fee348ffdea8820509d85171/main.go#L55
# Type: integer
# Mandatory: no
# Default: 9115
#
containerPort: 9115

# Specifies whether a ServiceAccount should be created.
# Type: boolean
# Mandatory: no
# Default: true
#
createServiceAccount: true

# Additional arguments for blackbox-exporter container.
# Type: list[string]
# Mandatory: no
# Default: []
#
extraArgs: []
#  - "--web.listen-address=:9115"
#  - "--timeout-offset=0.5"
#  - "--config.check=false"
#  - "--history.limit=100"
#  - "--web.external-url=http://example.com"
#  - "--web.route-prefix=/example/path"

serviceMonitor:
  # If true, a ServiceMonitor CRD is created for a prometheus operator.
  # Type: boolean
  # Mandatory: no
  # Default: true
  #
  enabled: true

  # Allow change metrics scrape interval.
  # Type: string
  # Mandatory: no
  #
  interval: 30s

  # Allow change metrics scrape timeout
  # Type: string
  # Mandatory: no
  #
  # Please note that scrapeTimeout must be less the interval
  scrapeTimeout: 30s

  # HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
  # Type: string
  # Mandatory: no
  # Default: http
  #
  scheme: http

  # DEPRECATED! Please use Probe CR instead.
  # Default values that will be used for all ServiceMonitors created by `targets`.
  # Type: object
  # Mandatory: no
  #
  defaults:
    additionalMetricsRelabels: {}
    interval: 30s
    # Please note that scrapeTimeout must be less the interval
    scrapeTimeout: 30s
    module: http_2xx

  # DEPRECATED! Please use Probe CR instead.
  # Parameters for each targets that will be created.
  # Type: list[object]
  # Mandatory: yes
  #
  targets: []
  #  - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
  #    url: http://example.com/healthz  # The URL that blackbox will scrape
  #    interval: 60s                    # Scraping interval. Overrides value set in `defaults`
  #    scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`. Must be less than interval
  #    module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
  #    additionalMetricsRelabels: {}    # Map of metric labels and values to add

# Allows to create Grafana dashboard for blackbox-exporter.
# Type: boolean
# Mandatory: no
# Default: true
#
grafanaDashboard: true

# SecurityContext holds pod-level security attributes.
# The parameters are required if a Pod Security Policy is enabled
# for Kubernetes cluster and required if a Security Context Constraints is enabled
# for Openshift cluster.
# Type: object
# Mandatory: no
#
# securityContext:
# The UID to run the entrypoint of the container process.
# Defaults to user specified in image metadata if unspecified.
# Type: integer
# Mandatory: no
#
# runAsUser: 2000

# A special supplemental group that applies to all containers in a pod.
# Some volume types allow the Kubelet to change the ownership of that volume
# to be owned by the pod:
#   1. The owning GID will be the FSGroup
#   2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
#   3. The permission bits are OR'd with rw-rw----
# If unset, the Kubelet will not modify the ownership and permissions of any volume.
# Type: integer
# Mandatory: no
#
# fsGroup: 2000

# Tolerations allow the pods to schedule onto nodes with matching taints.
# Type: object
# Mandatory: no
#
tolerations: []

# Allow define which Nodes the Pods are scheduled on.
# Type: map[string]
# Mandatory: no
# Default: not set
#
# nodeSelector: {}

# Annotations is an unstructured key value map stored
# with a resource that may be set by external tools to store and retrieve arbitrary metadata.
# They are not queryable and should be preserved when modifying objects.
# More info: https://kubernetes.io/docs/user-guide/annotations
# Type: map[string]string
# Mandatory: no
# Default: not set
#
annotations: {}
#  annotation-key: annotation-value

# Map of string keys and values that can be used to organize and categorize (scope and select) objects.
# May match selectors of replication controllers and services.
# More info: https://kubernetes.io/docs/user-guide/labels
# Type: map[string]string
# Mandatory: no
# Default: not set
#
labels: {}
#  label-key: label-value

# If specified, the pod's scheduling constraints
# More info: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#affinity-v1-core
# Type: object
# Mandatory: no
# Default: not set
#
affinity: {}

# PriorityClassName assigned to the Pods to prevent them from evicting.
# Type: string
# priorityClassName: "priorityClassName"