{{- if and .Values.integrationTests.install .Values.global.privilegedRights }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integrationTests.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "integrationTests.rbac.fullname" . }}
    app.kubernetes.io/component: platform-monitoring-tests
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "integrationTests.version" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.integrationTests.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "integrationTests.rbac.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
