{{- if .Values.integrationTests.install }}
{{- if eq (.Values.integrationTests.statusWriting.enabled | toString) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.integrationTests.name }}-write-status
  labels:
    app.kubernetes.io/name: {{ .Values.integrationTests.name }}-write-status
    app.kubernetes.io/component: platform-monitoring-tests
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "integrationTests.version" . }}
rules:
- apiGroups:
  - {{ template "integrationTests.apigroup_custom_resource" . }}
  resources:
  - {{ template "integrationTests.plural_custom_resource" . }}/status
  verbs:
  - get
  - patch
{{- end }}
{{- end }}
