{{- if .Values.integrationTests.install }}
{{- if eq (.Values.integrationTests.statusWriting.enabled | toString) "true" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.integrationTests.name }}-write-status
  labels:
    app.kubernetes.io/name: {{ .Values.integrationTests.name }}-write-status
    app.kubernetes.io/component: platform-monitoring-tests
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "integrationTests.version" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.integrationTests.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.integrationTests.name }}-write-status
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
