{{- if and .Values.install .Values.global.privilegedRights .Values.rbac.createClusterRole }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "networkLatencyExporter.rbac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "networkLatencyExporter.rbac.fullname" . }}
    app.kubernetes.io/component: network-latency-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "networkLatencyExporter.instance" . }}
    app.kubernetes.io/version: {{ template "networkLatencyExporter.version" . }}
rules:
  {{- if $.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
  - apiGroups:
      - "security.openshift.io"
    resources:
      - securitycontextconstraints
    resourceNames:
      - {{ .Release.Namespace }}-{{ .Values.name }}
    verbs:
      - 'use'
  {{- end }}
  {{- if $.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
  - apiGroups:
      - "policy"
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ .Release.Namespace }}-{{ .Values.name }}
    verbs:
      - 'use'
  {{- end }}
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - 'list'
      - 'watch'
{{- end }}
