{{- if and .Values.install .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/component: network-latency-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "networkLatencyExporter.instance" . }}
    app.kubernetes.io/version: {{ template "networkLatencyExporter.version" . }}
{{- end -}}