apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  labels:
    name: vmsingle
    app.kubernetes.io/name: vmsingle
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: k8s
spec:
  extraArgs:
    search.maxPointsPerTimeseries: "150000"
  replicaCount: 1
  resources: {}
  removePvcAfterDelete: true
  retentionPeriod: "14"
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
