apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core-dns-service-monitor
  labels:
    k8s-app: core-dns-service-monitor
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  endpoints:
    - interval: 30s
      scrapeTimeout: 10s
      metricRelabelings: []
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ['__meta_kubernetes_pod_node_name']
          targetLabel: node
      port: metrics
      path: /metrics
      scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
        kubernetes.io/name: CoreDNS
