apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-scheduler-service-monitor
  labels:
    k8s-app: kube-scheduler-service-monitor
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 10s
    metricRelabelings: []
    relabelings:
    - action: replace
      regex: (.+)(?::\d+)
      replacement: $1:10251
      sourceLabels: ['__address__']
      targetLabel: __address__
    port: https
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-scheduler
