apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-apiserver-operator-service-monitor
  labels:
    k8s-app: openshift-apiserver-operator
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: check-endpoints
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: component
  namespaceSelector:
    matchNames:
      - openshift-apiserver
  selector:
    matchLabels:
      prometheus: openshift-apiserver-check-endpoints