{{- if .Values.vmAgent.remoteWrite }}
{{- $top := . -}}
{{- range .Values.vmAgent.remoteWrite -}}
{{- if .basicAuth }}
{{- if .basicAuth.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .basicAuth.createSecret.secretName }}
  labels:
    app.kubernetes.io/name: {{ .basicAuth.createSecret.secretName }}
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ cat .basicAuth.createSecret.secretName "-" $.Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
stringData:
  username: {{ .basicAuth.createSecret.username }}
  password: {{ .basicAuth.createSecret.password }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
