apiVersion: v1
kind: Secret
metadata:
  name: vm-additional-scrape-configs
  labels:
    app.kubernetes.io/name: vm-additional-scrape-configs
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ cat "vm-additional-scrape-configs-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
{{- if .Values.vmAgent.additionalScrape }}
stringData:
  prometheus-additional.yaml: |-
    {{ toYaml .Values.vmAgent.additionalScrape | nindent 4 }}
{{- else }}
data:
  prometheus-additional.yaml: ""
{{- end }}
