{{- if and .Values.vmAgent.install .Values.vmAgent.extraVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vmAgent.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.vmAgent.secretName }}
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ cat .Values.vmAgent.secretName "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.vmAgent.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
{{- end }}
