{{- if and .Values.install (not .Values.aws.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: cloudwatch-exporter
    app.kubernetes.io/part-of: monitoring
type: Opaque
data:
  {{- if .Values.aws.aws_access_key_id }}
  aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.aws_secret_access_key }}
  aws_secret_access_key: {{ .Values.aws.aws_secret_access_key | b64enc | quote }}
  {{- end }}
{{- end }}