{{- if and .Values.install .Values.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/component: cloudwatch-exporter
    app.kubernetes.io/part-of: monitoring
  annotations:
  {{- if .Values.serviceAccount.annotations }}
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}