apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: {{ cat "blackbox-exporter-self-service-monitor-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "blackboxExporter.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
      port: http
      scheme: {{ .Values.serviceMonitor.scheme }}
  jobLabel: blackbox-exporter-self
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ .Values.name }}
