{{- if and .Values.install .Values.serviceMonitor.enabled }}
{{- range .Values.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Values.name }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ $.Values.name }}-{{ .name }}
    app.kubernetes.io/instance: {{ cat $.Values.name "-" .name "-" $.Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "blackboxExporter.image" $ }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
spec:
  endpoints:
  - port: http
    scheme: {{ $.Values.serviceMonitor.scheme }}
    path: "/probe"
    interval: {{ .interval | default $.Values.serviceMonitor.defaults.interval }}
    scrapeTimeout: {{ .scrapeTimeout | default $.Values.serviceMonitor.defaults.scrapeTimeout }}
    params:
      module:
      - {{ .module | default $.Values.serviceMonitor.defaults.module }}
      target:
      - {{ .url }}
    metricRelabelings:
      - targetLabel: instance
        replacement: {{ .url }}
      - targetLabel: target
        replacement: {{ .name }}
        {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $.Values.serviceMonitor.defaults.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel }}
        replacement: {{ $replacement }}
        {{- end }}
  jobLabel: {{ $.Values.name }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ $.Values.name }}
{{- end }}
{{- end }}
