{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphite-config
  labels:
    app.kubernetes.io/name: graphite-config
    app.kubernetes.io/instance: {{ cat "graphite-config-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: graphite-remote-adapter
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "graphiteRemoteAdapter.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
data:
  {{- if .Values.additionalGraphiteConfig }}
  additionalGraphiteConfig.yaml: |-
    {{- toYaml .Values.additionalGraphiteConfig | nindent 6 }}
  {{- else }}
  additionalGraphiteConfig.yaml: ""
  {{- end }}
{{- end }}

