{{- if .Values.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: graphite-remote-adapter
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "graphiteRemoteAdapter.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
{{- end }}