{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
  {{- if and .Values.install .Values.setupSecurityContext .Values.global.privilegedRights }}
    {{- with .Values }}
      {{- if or (and .certsInFiles .certsInFiles.enabled) (and .certsInKubeconfig .certsInKubeconfig.enabled) }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ template "certExporter.rbac.fullname" $ }}
  labels:
    app.kubernetes.io/name: {{ template "certExporter.rbac.fullname" $ }}
    app.kubernetes.io/component: cert-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "certExporter.instance" $ }}
    app.kubernetes.io/version: {{ template "certExporter.version" $ }}
priority: 0
users: []
groups: []
readOnlyRootFilesystem: true
requiredDropCapabilities: []
defaultAddCapabilities: []
allowedCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
allowPrivilegedContainer: false
allowHostDirVolumePlugin: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowHostIPC: false
volumes:
- '*'
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}