apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-kube-state-metrics
  labels:
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: monitoring-kube-state-metrics
