apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-kube-state-metrics
  labels:
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator