apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    platform.monitoring.app: kube-state-metrics
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
    - name: telemetry
      port: 8081
      targetPort: telemetry
      protocol: TCP
  selector:
    platform.monitoring.app: kube-state-metrics