{{- if .Values.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: stackdriver-exporter
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "stackdriver-exporter.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/component: stackdriver-exporter
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/version: {{ splitList ":" $image | last }}
        app.kubernetes.io/managed-by: Helm
        {{- if .Values.labels }}
          {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{ include "stackdriver-exporter.securityContext" . }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      serviceAccount: {{ .Values.serviceAccount.name }}
      volumes:
      {{- if .Values.stackdriver.serviceAccountSecret }}
        - name: stackdriver-service-account
          secret:
            secretName: {{ .Values.stackdriver.serviceAccountSecret | quote }}
            {{- if and (.Values.stackdriver.serviceAccountSecret) (.Values.stackdriver.serviceAccountSecretKey) }}
            items:
              - key: {{ .Values.stackdriver.serviceAccountSecretKey | quote }}
                path: credentials.json
            {{- end }}
      {{- else if .Values.stackdriver.serviceAccountKey }}
        - name: stackdriver-service-account
          secret:
            secretName: {{ .Values.name }}
      {{- end}}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ template "stackdriver-exporter.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["stackdriver_exporter"]
          volumeMounts:
          {{- if or .Values.stackdriver.serviceAccountSecret .Values.stackdriver.serviceAccountKey }}
            - name: stackdriver-service-account
              mountPath: /etc/secrets/service-account/
          {{- end}}
          args:
            - --google.project-id={{ .Values.stackdriver.projectId }}
            - --monitoring.metrics-interval={{ .Values.stackdriver.metrics.interval }}
            - --monitoring.metrics-offset={{ .Values.stackdriver.metrics.offset }}
            - --monitoring.metrics-type-prefixes={{ .Values.stackdriver.metrics.typePrefixes }}
            - --stackdriver.backoff-jitter={{ .Values.stackdriver.backoffJitter }}
            - --stackdriver.http-timeout={{ .Values.stackdriver.httpTimeout }}
            - --stackdriver.max-backoff={{ .Values.stackdriver.maxBackoff }}
            - --stackdriver.max-retries={{ .Values.stackdriver.maxRetries }}
            - --stackdriver.retry-statuses={{ .Values.stackdriver.retryStatuses }}
            - --web.listen-address=:9255
            - --web.telemetry-path=/metrics
          {{- if .Values.stackdriver.dropDelegatedProjects }}
            - --monitoring.drop-delegated-projects
          {{- end }}
          {{- if .Values.stackdriver.metrics.ingestDelay }}
            - --monitoring.metrics-ingest-delay
          {{- end }}
          {{- if .Values.extraArgs }}
            {{ toYaml .Values.extraArgs | nindent 12 }}
          {{- end }}
          {{- if or .Values.stackdriver.serviceAccountSecret .Values.stackdriver.serviceAccountKey }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secrets/service-account/credentials.json
          {{- end }}
          resources:
            {{ include "stackdriverExporter.resources" $ }}
          ports:
            - containerPort: 9255
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
