{{- if and .Values.install .Values.stackdriver.serviceAccountKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: stackdriver-exporter
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "stackdriver-exporter.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
type: Opaque
data:
  credentials.json: {{ .Values.stackdriver.serviceAccountKey | b64enc | quote }}
{{- end }}
