{{- if .Values.install }}
{{- $metrics := toYaml .Values.metrics -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: promitor-agent-scraper
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "promitor.agentScraper.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
data:
  runtime.yaml: |-
      server:
        httpPort: {{ .Values.service.targetPort | quote }}
      authentication:
        mode: {{ .Values.azureAuthentication.mode | default "ServicePrincipal"}}
  {{- if .Values.azureAuthentication.identity.id }}
        identityId: {{ .Values.azureAuthentication.identity.id}}
  {{- end }}
  {{- if .Values.resourceDiscovery.enabled }}
      resourceDiscovery:
        host: {{ .Values.resourceDiscovery.host | quote }}
        port: {{ .Values.resourceDiscovery.port }}
  {{- end }}
      metricSinks:
        prometheusScrapingEndpoint:
          metricUnavailableValue: {{ .Values.metricSinks.prometheusScrapingEndpoint.metricUnavailableValue | quote }}
          enableMetricTimestamps: {{ .Values.metricSinks.prometheusScrapingEndpoint.enableMetricTimestamps | quote }}
          baseUriPath: {{ .Values.metricSinks.prometheusScrapingEndpoint.baseUriPath | quote }}
          labels:
            transformation: {{ .Values.metricSinks.prometheusScrapingEndpoint.labelTransformation | quote }}
      metricsConfiguration:
        absolutePath: /config/metrics-declaration.yaml
      telemetry:
        applicationInsights:
  {{- if .Values.telemetry.applicationInsights.key }}
          instrumentationKey: {{ .Values.telemetry.applicationInsights.key | quote }}
  {{- end }}
          isEnabled: {{ .Values.telemetry.applicationInsights.enabled | quote }}
  {{- if .Values.telemetry.applicationInsights.logLevel }}
          verbosity: {{ .Values.telemetry.applicationInsights.logLevel | quote }}
  {{- end }}
        containerLogs:
          isEnabled: {{ .Values.telemetry.containerLogs.enabled | quote }}
  {{- if .Values.telemetry.containerLogs.logLevel  }}
          verbosity: {{ .Values.telemetry.containerLogs.logLevel | quote }}
  {{- end }}
        defaultVerbosity: {{ .Values.telemetry.defaultLogLevel | quote  }}
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId: {{ .Values.azureMetadata.tenantId }}
      subscriptionId: {{ .Values.azureMetadata.subscriptionId }}
      resourceGroupName: {{ .Values.azureMetadata.resourceGroupName }}
      cloud: {{ .Values.azureMetadata.cloud }}
    metricDefaults:
      aggregation:
        interval: {{ .Values.metricDefaults.aggregation.interval }}
      scraping:
        schedule: {{ .Values.metricDefaults.scraping.schedule | quote }}
    metrics:{{- if .Values.metrics | len | eq 0 }} []{{- else }}
    {{ tpl $metrics . | nindent 4 }}
    {{- end }}
{{- end }}
