{{- if .Values.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: promitor-agent-scraper
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "promitor.agentScraper.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
    {{- if .Values.labels }}
      {{ toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/component: promitor-agent-scraper
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/version: {{ splitList ":" $image | last }}
        app.kubernetes.io/managed-by: Helm
        {{- if .Values.labels }}
          {{ toYaml .Values.labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ .Files.Get "templates/promitor-agent-scraper/configmap.yaml" | sha256sum }}
        checksum/secrets: {{ .Files.Get "templates/promitor-agent-scraper/secrets.yaml" | sha256sum }}
        {{- if .Values.annotations }}
          {{ toYaml .Values.annotations | nindent 8 }}
        {{- end }}
        {{- if empty .Values.azureAuthentication.identity.binding | not }}
        aadpodidbinding: {{ .Values.azureAuthentication.identity.binding }}
        {{- end }}
    spec:
      securityContext:
        {{ include "promitor.agentScraper.securityContext" . }}
      {{- if .Values.serviceAccount.install }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume-{{ .Values.name }}
          configMap:
            name: {{ .Values.name }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ template "promitor.agentScraper.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          {{- if or (.Values.azureAuthentication.identity.key) (eq .Values.secrets.createSecret false) }}
          - name: PROMITOR_AUTH_APPKEY
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: {{ .Values.secrets.appKeySecret }}
          {{- end}}
          resources:
            {{ include "promitor.agentScraper.resources" $ }}
          volumeMounts:
          - name: config-volume-{{ .Values.name }}
            mountPath: /config/
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health?includeDependencies=false
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health?includeDependencies=false
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
{{- end }}
