{{- if and .Values.install .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  labels:
    app.kubernetes.io/name: {{ .Values.secrets.secretName }}
    app.kubernetes.io/instance: {{ cat .Values.secrets.secretName "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: promitor-agent-scraper
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "promitor.agentScraper.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
type: Opaque
data:
  {{- if .Values.azureAuthentication.identity.key}}
  {{ .Values.secrets.appKeySecret  }}: {{ .Values.azureAuthentication.identity.key | b64enc | quote }}
  {{- end }}
{{- end }}
