apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    platform.monitoring.app: pushgateway
    app.kubernetes.io/component: pushgateway
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  annotations: {}
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      platform.monitoring.app: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pushgateway
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: monitoring-operator
        platform.monitoring.app: pushgateway
      annotations: {}
    spec:
      containers:
        - name: pushgateway
          args: []
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
