apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pushgateway
  labels:
    platform.monitoring.app: pushgateway
    app.kubernetes.io/component: pushgateway
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
