apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
  labels:
    name: grafana-operator
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: grafana-operator
        app.kubernetes.io/component: grafana
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: monitoring-operator
    spec:
      containers:
        - command:
            - /manager
          env:
            - name: TEMPLATE_PATH
              value: /usr/local/bin/templates
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: grafana-operator
          image: grafana-operator/grafana-operator:v4.1.1
          imagePullPolicy: IfNotPresent
          name: grafana-operator
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      securityContext: {}
      serviceAccount: grafana-operator
      serviceAccountName: grafana-operator
      terminationGracePeriodSeconds: 30
