apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: grafana-operator-pod-monitor
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: metrics
    scheme: http
  jobLabel: grafana-operator-pod-monitor
  namespaceSelector: {}
  selector:
    matchLabels:
      name: grafana-operator
