kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
subjects:
  - kind: ServiceAccount
    name: grafana-operator
roleRef:
  kind: Role
  name: platform-monitring-grafana-operator
  apiGroup: rbac.authorization.k8s.io
