apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
